apiVersion: v1
kind: Pod
metadata:
  name: meupod
  labels:
    app: nginx-color
spec:
  containers:
  - name: nginx-color
    image: kubedevio/nginx-color:blue
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
