apiVersion: v1
kind: Pod
metadata:
  name: meupod2
spec:
  containers:
  - name: nginx-color
    image: kubedevio/nginx-color:green
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
